# Introduction To Recommender System
## With Python

In [1]:
import numpy as np

In [2]:
np.random.random?

In [3]:
a = np.random.random(100)
b = np.random.random(100)

In [4]:
c = a + b
print c.shape
d = a - b
print d.shape

(100,)
(100,)


In [5]:
from scipy.spatial import distance

In [6]:
distance.cosine(a, b)

0.21756732930279543

# Standard Cases in Similarity

In [19]:
from scipy import stats

In [30]:
part_1_1 = stats.poisson.rvs(2, size=5) # Customer 1 gives lower ratings to first 5 movies / products
part_2_1 = stats.poisson.rvs(8, size=5) # Customer 1 gives higher ratings to last 5 movies / products
cust_1 = np.hstack([part_1_1, part_2_1])
print cust_1

[ 1  2  1  1  2 11  4  6  7  9]


In [31]:
part_1_2 = stats.poisson.rvs(8, size=5) # Customer 2 gives higher ratings to first 5 movies / products
part_2_2 = stats.poisson.rvs(2, size=5) # Customer 2 gives lower ratings to last 5 movies / products
cust_2 = np.hstack([part_1_2, part_2_2])
print cust_2

[ 3 13  8  6  4  1  2  3  3  3]


In [32]:
part_1_3 = stats.poisson.rvs(2, size=5) # Customer 3 gives lower ratings to first 5 movies / products
part_2_3 = stats.poisson.rvs(8, size=5) # Customer 3 gives higher ratings to last 5 movies / products
cust_3 = np.hstack([part_1_3, part_2_3])
print cust_3

[ 4  3  2  3  6 10  9  8 11 11]


In [48]:
print distance.cosine(cust_1, cust_2)
print distance.cosine(cust_1, cust_3)

0.574925273265
0.0541021200104


In [50]:
assert(distance.cosine(cust_1, cust_2) > distance.cosine(cust_1, cust_3) )

In [ ]:
## Now show the same code as above in a matrix form to generate similarity matrix
## After that build similary index lookup / nearest neighbour
## Conclude the first iteration

In [ ]:
## Repeat the experiment with larger data like 20 newsgroups
## Filter by top 500 tokens or so
## Show that actually relevant documents get picked up

In [ ]:
## Expect the users to follow along till 20 newsgroups
## After that cover ALS, Rendle as theory
## Go back to nearest neighbours
